[tool.black]
line-length = 120
target-version = ['py39']
include = '\.py$'
exclude = '''
(
      \.git
    | \.venv
    | __pycache__
    | data
    | docs
    | spec
    | build
    | dist
    | venv
)
'''
[tool.pylint]
max-line-length = 120
max-module-lines = 1000